name: 'The Cleaner (Stale)'
on:
  schedule:
    - cron: '30 1 * * *' # Run daily at 1:30 AM
  workflow_dispatch:

permissions:
  issues: write
  pull-requests: write

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          stale-issue-message: 'This issue is stale because it has been open 60 days with no activity. Remove stale label or comment or this will be closed in 7 days.'
          stale-issue-label: 'status:stale'
          days-before-stale: 60
          days-before-close: 7
          close-issue-message: 'This issue was closed because it has been stalled for 7 days with no activity.'
          exempt-issue-labels: 'status:pinned,type:security'
          operations-per-run: 50
